# Generated by Django 5.1.1 on 2024-10-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laundrycloth',
            options={'verbose_name_plural': 'Laundry Clothes'},
        ),
    ]
