# Generated by Django 5.1.1 on 2024-10-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_management', '0002_alter_laundrycloth_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryevent',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
