# Generated by Django 5.1.1 on 2024-10-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_management', '0003_laundryevent_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrycloth',
            name='image',
            field=models.ImageField(upload_to='media/laundry_clothes/'),
        ),
    ]
