# Generated by Django 5.1.1 on 2024-10-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_management', '0004_alter_laundrycloth_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrycloth',
            name='ready_on',
            field=models.DateTimeField(null=True),
        ),
    ]
